/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.border.LineBorder;
import clases.DataBase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jefry
 */
public class Login extends javax.swing.JFrame {

    DataBase bata_base;
    String usuario_activo;
    String rol_ususario_activo;
    String nombre_usuario;
    public Login() {
        bata_base = new DataBase();
        usuario_activo="";
        nombre_usuario="";
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_cedula = new javax.swing.JTextField();
        l_img_correo = new javax.swing.JLabel();
        l_img_llave = new javax.swing.JLabel();
        l_fecha = new javax.swing.JLabel();
        campo_contrasenia = new javax.swing.JPasswordField();
        label_imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESA A NUESTRA APP");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO:");

        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA:");

        campo_cedula.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        campo_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_cedulaActionPerformed(evt);
            }
        });

        l_fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l_fechaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_fechaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_fechaMouseExited(evt);
            }
        });

        campo_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_contraseniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                                .addComponent(l_img_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                                .addComponent(l_img_llave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                        .addComponent(l_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_img_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campo_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_loginLayout.createSequentialGroup()
                        .addComponent(l_img_llave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                        .addComponent(campo_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(l_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        getContentPane().add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 350, 320));
        getContentPane().add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void l_fechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_fechaMouseEntered
        Image img_flecha = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/flecha.png"));
        img_flecha = img_flecha.getScaledInstance(85, 80, Image.SCALE_SMOOTH);
        l_fecha.setBackground(new Color(0, 0, 0, (int) (255 * (1 - 1))));
        l_fecha.setIcon(new ImageIcon(img_flecha));
        revalidate();
        repaint();
    }//GEN-LAST:event_l_fechaMouseEntered

    private void l_fechaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_fechaMouseExited
        Image img_flecha = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/flecha.png"));
        img_flecha = img_flecha.getScaledInstance(65, 60, Image.SCALE_SMOOTH);
        l_fecha.setIcon(new ImageIcon(img_flecha));
        l_fecha.setBackground(new Color(0, 0, 0, (int) (255 * (1 - 1))));
        revalidate();
        repaint();
    }//GEN-LAST:event_l_fechaMouseExited

    private void l_fechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_fechaMouseClicked
        String cedula = campo_cedula.getText();
        String contrasenia = campo_contrasenia.getText();

        ResultSet datos_usuario = bata_base.iniciarSesion(cedula,contrasenia);

        if(datos_usuario != null){
            usuario_activo = cedula;
            
            try {
                rol_ususario_activo = datos_usuario.getString("rol");
                nombre_usuario = datos_usuario.getString("nombre");
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            panel_login.setVisible(false);
            Image img_login = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/loader.gif"));
            label_imagen.setIcon(new ImageIcon(img_login));
            revalidate();
            repaint();
            
            Timer timer = new Timer(3000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Mesas temporal = new Mesas(bata_base,usuario_activo,rol_ususario_activo,nombre_usuario);
                    dispose();
                }
            });
            
            timer.setRepeats(false); // Para que solo se ejecute una vez
            timer.start();
        }
        
        
        
        
        
    }//GEN-LAST:event_l_fechaMouseClicked

    private void campo_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_cedulaActionPerformed

    private void campo_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_contraseniaActionPerformed
    public void alternInitComponents(){
        Image restaurante_logo2 = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/restaurante_logo2.png"));
        restaurante_logo2 = restaurante_logo2.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        this.setIconImage(restaurante_logo2);
        
        
        Image img_login = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/login.jpg"));
        img_login = img_login.getScaledInstance(800, 480, Image.SCALE_SMOOTH);
        label_imagen.setIcon(new ImageIcon(img_login));
        
        Image img_correo = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/correo.png"));
        img_correo = img_correo.getScaledInstance(30, 25, Image.SCALE_SMOOTH);
        l_img_correo.setIcon(new ImageIcon(img_correo));
        
        Image img_candado = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/candado.png"));
        img_candado = img_candado.getScaledInstance(35, 30, Image.SCALE_SMOOTH);
        l_img_llave.setIcon(new ImageIcon(img_candado));
        
        Image img_flecha = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/flecha.png"));
        img_flecha = img_flecha.getScaledInstance(65, 60, Image.SCALE_SMOOTH);
        l_fecha.setIcon(new ImageIcon(img_flecha));
        l_fecha.setBackground(new Color(0, 0, 0, (int) (255 * (1 - 1))));
                
        Image gif_loader = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/loader.gif"));

        
        panel_login.setBackground(new Color(0, 0, 0, (int) (255 * (1 - 0.6))));
        Color color_borde = new Color(0, 0, 0, 2);
        panel_login.setBorder(new LineBorder(color_borde, 5));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_cedula;
    private javax.swing.JPasswordField campo_contrasenia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l_fecha;
    private javax.swing.JLabel l_img_correo;
    private javax.swing.JLabel l_img_llave;
    public javax.swing.JLabel label_imagen;
    private javax.swing.JPanel panel_login;
    // End of variables declaration//GEN-END:variables
}
