
package ui;

import clases.DataBase;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;



public class Mesas extends javax.swing.JFrame {

    DataBase data_base;
    String usuario_activo;
    String rol_usuario_activo;
    String nombre_usuario;
    public Mesas(DataBase data_base,String usuario_activo,String rol_usuario_activo,String nombre_usuario) {
        this.nombre_usuario = nombre_usuario;
        this.rol_usuario_activo = rol_usuario_activo;
        this.usuario_activo = usuario_activo;
        this.data_base=data_base;
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_pedido = new javax.swing.JButton();
        btn_verPedido = new javax.swing.JButton();
        btn_verPedido1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label_imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 660, 370));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel2.setText("RESTAURANTE L . J");

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setFocusable(false);
        btn_login.setOpaque(true);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_registrar.setBackground(new java.awt.Color(0, 0, 0));
        btn_registrar.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_registrar.setText("REGISTRAR");
        btn_registrar.setFocusable(false);
        btn_registrar.setOpaque(true);
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        btn_menu.setBackground(new java.awt.Color(0, 0, 0));
        btn_menu.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn_menu.setText("MENÚ");
        btn_menu.setFocusable(false);
        btn_menu.setOpaque(true);
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_pedido.setBackground(new java.awt.Color(0, 0, 0));
        btn_pedido.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_pedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_pedido.setText("PEDIDO");
        btn_pedido.setFocusable(false);
        btn_pedido.setOpaque(true);
        btn_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedidoActionPerformed(evt);
            }
        });

        btn_verPedido.setBackground(new java.awt.Color(0, 0, 0));
        btn_verPedido.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_verPedido.setForeground(new java.awt.Color(255, 255, 255));
        btn_verPedido.setText("PLATOS");
        btn_verPedido.setFocusable(false);
        btn_verPedido.setOpaque(true);
        btn_verPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verPedidoActionPerformed(evt);
            }
        });

        btn_verPedido1.setBackground(new java.awt.Color(0, 0, 0));
        btn_verPedido1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        btn_verPedido1.setForeground(new java.awt.Color(255, 255, 255));
        btn_verPedido1.setText("MESAS");
        btn_verPedido1.setFocusable(false);
        btn_verPedido1.setOpaque(true);
        btn_verPedido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verPedido1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_registrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_verPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_verPedido1)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_registrar)
                    .addComponent(btn_menu)
                    .addComponent(btn_pedido)
                    .addComponent(btn_verPedido)
                    .addComponent(btn_verPedido1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));
        getContentPane().add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        Login temporal = new Login();
        dispose();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
       jPanel1.removeAll();
       PanelRegistrar temporal = new PanelRegistrar(data_base,this);
       temporal.setSize(jPanel1.getSize());
       jPanel1.add(temporal);
       repaint();
       revalidate();
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        jPanel1.removeAll();
        PanelMenu temporal = new PanelMenu(data_base,0,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        repaint();
        revalidate();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedidoActionPerformed
        jPanel1.removeAll();
        PanelPedido temporal = new PanelPedido(data_base,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        repaint();
        revalidate();
    }//GEN-LAST:event_btn_pedidoActionPerformed

    private void btn_verPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verPedidoActionPerformed
        jPanel1.removeAll();
        PanelCrearPlato temporal = new PanelCrearPlato(data_base,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        repaint();
        revalidate();
    }//GEN-LAST:event_btn_verPedidoActionPerformed

    private void btn_verPedido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verPedido1ActionPerformed
        jPanel1.removeAll();
        PanelMesa temporal = new PanelMesa(data_base,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_btn_verPedido1ActionPerformed
    public void alternInitComponents(){
        Image restaurante_logo2 = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/restaurante_logo2.png"));
        restaurante_logo2 = restaurante_logo2.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        this.setIconImage(restaurante_logo2);
        this.setTitle("RESTAURANTE L.J");
        
        
        
        Image foto_usuario_admin = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/admin.png"));
        foto_usuario_admin = foto_usuario_admin.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
        jLabel1.setIcon(new ImageIcon(foto_usuario_admin));
        jLabel3.setText("ROL: "+rol_usuario_activo+" "+nombre_usuario);
        
        if(rol_usuario_activo.equals("cajero")){
            Image foto_usuario_cajero = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/cajero.png"));
            foto_usuario_cajero = foto_usuario_cajero.getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(foto_usuario_cajero));
            btn_registrar.setEnabled(false);
        }
        Image img_login = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/img_mesas.jpg"));
        img_login = img_login.getScaledInstance(800, 480, Image.SCALE_SMOOTH);
        label_imagen.setIcon(new ImageIcon(img_login));
        
        jPanel1.removeAll();
        PanelMesa temporal = new PanelMesa(data_base,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        repaint();
        revalidate();
        
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.revalidate();
    }

    public void removerPanel(int numero_mesa){
        this.jPanel1.removeAll();
        PanelMenu temporal = new PanelMenu(data_base,numero_mesa,this);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        this.repaint();
        this.revalidate();
    }
    public void removerPanelPedido(int n_factura){
        this.jPanel1.removeAll();
        PanelVerPedido temporal = new PanelVerPedido(data_base,this,n_factura);
        temporal.setSize(jPanel1.getSize());
        jPanel1.add(temporal);
        this.repaint();
        this.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_pedido;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_verPedido;
    private javax.swing.JButton btn_verPedido1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel label_imagen;
    // End of variables declaration//GEN-END:variables
}
