/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.DataBase;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author INSTRUCTOR
 */
public class PanelRegistrar extends javax.swing.JPanel {

    DataBase data_base;
    Mesas mesas;
    public PanelRegistrar(DataBase data_base,Mesas mesas) {
        this.mesas = mesas;
        this.data_base = data_base;
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_nombre = new javax.swing.JLabel();
        c_nombre = new javax.swing.JTextField();
        l_apellido = new javax.swing.JLabel();
        l_contrasena = new javax.swing.JLabel();
        l_cedula = new javax.swing.JLabel();
        c_apellido = new javax.swing.JTextField();
        c_contrasenia = new javax.swing.JTextField();
        c_cedula = new javax.swing.JTextField();
        l_btn_elinimar = new javax.swing.JLabel();
        l_btn_editar = new javax.swing.JLabel();
        l_btn_ok = new javax.swing.JLabel();
        l_respuesta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        l_nombre.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_nombre.setForeground(new java.awt.Color(255, 255, 255));
        l_nombre.setText("NOMBRE:");

        c_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nombreActionPerformed(evt);
            }
        });

        l_apellido.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_apellido.setForeground(new java.awt.Color(255, 255, 255));
        l_apellido.setText("APELLIDO:");

        l_contrasena.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        l_contrasena.setText("CONTRASEÑA:");

        l_cedula.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_cedula.setForeground(new java.awt.Color(255, 255, 255));
        l_cedula.setText("CÉDULA:");

        c_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_apellidoActionPerformed(evt);
            }
        });

        c_contrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_contraseniaActionPerformed(evt);
            }
        });

        c_cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cedulaActionPerformed(evt);
            }
        });

        l_btn_elinimar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_elinimar.setOpaque(true);

        l_btn_editar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_editar.setOpaque(true);
        l_btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarUsuario(evt);
            }
        });

        l_btn_ok.setText("jLabel5");
        l_btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarPersona(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(l_cedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                    .addComponent(l_contrasena)
                    .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(c_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(c_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(c_contrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(c_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(l_respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nombreActionPerformed

    private void c_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_apellidoActionPerformed

    private void c_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_contraseniaActionPerformed

    private void c_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cedulaActionPerformed

    private void registrarPersona(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarPersona
        String nombre = c_nombre.getText();
        String apellido = c_apellido.getText();
        String cedula = c_cedula.getText();
        String contrasenia = c_contrasenia.getText();
        if(nombre != null && !"".equals(nombre) && apellido != null && !"".equals(apellido) && cedula != null && !"".equals(cedula) && contrasenia != null && !"".equals(contrasenia)){
            boolean respuesta = data_base.insertarUsuario(cedula, nombre, apellido, contrasenia, "cajero");
            if(respuesta){
                l_respuesta.setText("Usuario creado");
                this.c_nombre.setText("");
                this.c_apellido.setText("");
                this.c_cedula.setText("");
                this.c_contrasenia.setText("");
            }
        }else{
            System.out.println("Los campos no pueden estar vacios");
        }
    }//GEN-LAST:event_registrarPersona

    private void editarUsuario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarUsuario
       this.removeAll();
       PanelEditar temporal = new PanelEditar(data_base,mesas);
       temporal.setSize(this.getSize());
       this.add(temporal);
       mesas.repaint();
       mesas.revalidate();
    }//GEN-LAST:event_editarUsuario
    
    
    public void alternInitComponents(){
        
        Image btn_eliminar = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_eliminar.png"));
        btn_eliminar = btn_eliminar.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_elinimar.setIcon(new ImageIcon(btn_eliminar));
        
        Image btn_editar = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_editar.png"));
        btn_editar = btn_editar.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_editar.setIcon(new ImageIcon(btn_editar));
        
        Image btn_ok = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_ok.png"));
        btn_ok = btn_ok.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_ok.setIcon(new ImageIcon(btn_ok));
        
        this.setBackground(new Color (0, 0, 0, (int) (255 * (1 - 0.6))));
        
        Border emptyBorder = new EmptyBorder(0, 7, 0, 0);        
        l_btn_elinimar.setBorder(emptyBorder);       
        l_btn_editar.setBorder(emptyBorder);

        this.setVisible(true);
        this.revalidate();
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_apellido;
    private javax.swing.JTextField c_cedula;
    private javax.swing.JTextField c_contrasenia;
    private javax.swing.JTextField c_nombre;
    private javax.swing.JLabel l_apellido;
    private javax.swing.JLabel l_btn_editar;
    private javax.swing.JLabel l_btn_elinimar;
    private javax.swing.JLabel l_btn_ok;
    private javax.swing.JLabel l_cedula;
    private javax.swing.JLabel l_contrasena;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_respuesta;
    // End of variables declaration//GEN-END:variables
}
