/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.DataBase;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author INSTRUCTOR
 */
public class PanelEditarPlato extends javax.swing.JPanel {

    DataBase data_base;
    Mesas mesas;
    public PanelEditarPlato(DataBase data_base,Mesas mesas) {
        this.mesas = mesas;
        this.data_base = data_base;
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c_nombre_plato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_descripcion_plato = new javax.swing.JTextField();
        c_precio_plato = new javax.swing.JTextField();
        l_btn_elinimar = new javax.swing.JLabel();
        l_btn_editar = new javax.swing.JLabel();
        l_btn_ok = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c_id_plato = new javax.swing.JTextField();
        l_respuesta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE:");

        c_nombre_plato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_nombre_plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nombre_platoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DESCRIPCIÓN:");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PRECIO:");

        c_descripcion_plato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_descripcion_plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_descripcion_platoActionPerformed(evt);
            }
        });

        c_precio_plato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_precio_plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_precio_platoActionPerformed(evt);
            }
        });

        l_btn_elinimar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_elinimar.setOpaque(true);

        l_btn_editar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_editar.setOpaque(true);
        l_btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearPlato(evt);
            }
        });

        l_btn_ok.setText("jLabel5");
        l_btn_ok.setEnabled(false);
        l_btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarPlato(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID PLATO:");

        c_id_plato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_id_plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_id_platoActionPerformed(evt);
            }
        });
        c_id_plato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarPlato(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(c_descripcion_plato, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(c_precio_plato, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(c_nombre_plato, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(l_respuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(c_id_plato, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_id_plato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_nombre_plato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_descripcion_plato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_precio_plato, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_nombre_platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nombre_platoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nombre_platoActionPerformed

    private void c_descripcion_platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_descripcion_platoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_descripcion_platoActionPerformed

    private void c_precio_platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_precio_platoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_precio_platoActionPerformed

    private void c_id_platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_id_platoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_id_platoActionPerformed

    private void crearPlato(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearPlato
       this.removeAll();
       PanelCrearPlato temporal = new PanelCrearPlato(data_base,mesas);
       temporal.setSize(this.getSize());
       this.add(temporal);
       mesas.repaint();
       mesas.revalidate();
    }//GEN-LAST:event_crearPlato

    private void editarPlato(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarPlato
        String id_plato = c_id_plato.getText();
        String nombre_plato = c_nombre_plato.getText();
        String descripcion_plato = c_descripcion_plato.getText();
        String precio_plato = c_precio_plato.getText();
        boolean respuesta = data_base.editarPlato(Integer.parseInt(id_plato), nombre_plato, descripcion_plato, Integer.parseInt(precio_plato));
        if(respuesta){
            l_respuesta.setText("editado");
            this.c_id_plato.setText("");
            this.c_nombre_plato.setText("");
            this.c_descripcion_plato.setText("");
            this.c_precio_plato.setText("");
        }
    }//GEN-LAST:event_editarPlato

    private void buscarPlato(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarPlato
        String id_plato = c_id_plato.getText();
        ResultSet respusta = data_base.buscarPlato(Integer.parseInt(id_plato));
        if (respusta != null && id_plato != null && !"".equals(id_plato)){
            try { 
                c_id_plato.setText(respusta.getString("id_plato"));
                c_nombre_plato.setText(respusta.getString("nombre"));
                c_descripcion_plato.setText(respusta.getString("descripcion"));
                c_precio_plato.setText(respusta.getString("precio"));
                l_btn_editar.enableInputMethods(true);
            } catch (SQLException ex) {
                System.out.println("no existe ese campo que buscas en la db");
            }
        }
    }//GEN-LAST:event_buscarPlato
    
    
    public void alternInitComponents(){
        
        Image edit = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/edit.png"));
        edit = edit.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_elinimar.setIcon(new ImageIcon(edit));
        
        Image btn_editar = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_editar.png"));
        btn_editar = btn_editar.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_editar.setIcon(new ImageIcon(btn_editar));
        
        Image btn_ok = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_ok.png"));
        btn_ok = btn_ok.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_ok.setIcon(new ImageIcon(btn_ok));
        
        this.setBackground(new Color (0, 0, 0, (int) (255 * (1 - 0.6))));
        
        Border emptyBorder = new EmptyBorder(0, 7, 0, 0);        
        l_btn_elinimar.setBorder(emptyBorder);       
        l_btn_editar.setBorder(emptyBorder);

        this.setVisible(true);
        this.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_descripcion_plato;
    private javax.swing.JTextField c_id_plato;
    private javax.swing.JTextField c_nombre_plato;
    private javax.swing.JTextField c_precio_plato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l_btn_editar;
    private javax.swing.JLabel l_btn_elinimar;
    private javax.swing.JLabel l_btn_ok;
    private javax.swing.JLabel l_respuesta;
    // End of variables declaration//GEN-END:variables
}
