/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.DataBase;
import java.awt.Color;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author INSTRUCTOR
 */
public class PanelEditar extends javax.swing.JPanel {

    DataBase data_base;
    Mesas mesa;
    public PanelEditar(DataBase data_base, Mesas mesa) {
        this.mesa = mesa;
        this.data_base = data_base;
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_cedula = new javax.swing.JLabel();
        c_cedula = new javax.swing.JTextField();
        l_nombre = new javax.swing.JLabel();
        l_contrasena = new javax.swing.JLabel();
        l_apellido = new javax.swing.JLabel();
        c_nombre = new javax.swing.JTextField();
        c_contrasena = new javax.swing.JTextField();
        c_apellido = new javax.swing.JTextField();
        l_btn_elinimar = new javax.swing.JLabel();
        l_btn_editar = new javax.swing.JLabel();
        l_btn_ok = new javax.swing.JLabel();
        l_contrasena1 = new javax.swing.JLabel();
        c_rol = new javax.swing.JTextField();
        l_respusta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        l_cedula.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_cedula.setForeground(new java.awt.Color(255, 255, 255));
        l_cedula.setText("CEDULA:");

        c_cedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_cedulaActionPerformed(evt);
            }
        });
        c_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarPersona(evt);
            }
        });

        l_nombre.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_nombre.setForeground(new java.awt.Color(255, 255, 255));
        l_nombre.setText("NOMBRE:");

        l_contrasena.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        l_contrasena.setText("CONTRASEÑA:");

        l_apellido.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_apellido.setForeground(new java.awt.Color(255, 255, 255));
        l_apellido.setText("APELLIDO:");

        c_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nombreActionPerformed(evt);
            }
        });

        c_contrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_contrasenaActionPerformed(evt);
            }
        });

        c_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_apellidoActionPerformed(evt);
            }
        });

        l_btn_elinimar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_elinimar.setOpaque(true);

        l_btn_editar.setBackground(new java.awt.Color(0, 0, 0));
        l_btn_editar.setOpaque(true);

        l_btn_ok.setEnabled(false);
        l_btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarUsuario(evt);
            }
        });

        l_contrasena1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        l_contrasena1.setForeground(new java.awt.Color(255, 255, 255));
        l_contrasena1.setText("ESTADO:");

        c_rol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        c_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_rolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(l_apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(l_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                            .addComponent(l_contrasena)
                            .addComponent(l_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_contrasena1)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_respusta, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(l_btn_elinimar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(l_btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(l_btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_contrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_respusta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_cedulaActionPerformed

    private void c_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nombreActionPerformed

    private void c_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_contrasenaActionPerformed

    private void c_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_apellidoActionPerformed

    private void editarUsuario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarUsuario

        String c_cedula = this.c_cedula.getText();
        String c_nombre = this.c_nombre.getText();
        String c_apellido = this.c_apellido.getText();
        String c_contrasena = this.c_contrasena.getText();
        String estado = this.c_rol.getText();
        
        boolean respuesta = data_base.editarPersona(c_cedula, c_nombre, c_apellido, c_contrasena,Integer.parseInt(estado));
        if(respuesta){
            l_respusta.setText("Usuario editado");
            this.c_cedula.setText("");
            this.c_nombre.setText("");
            this.c_apellido.setText("");
            this.c_contrasena.setText("");
            this.c_rol.setText("");
        }
    }//GEN-LAST:event_editarUsuario

    private void buscarPersona(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarPersona
        String cedula = c_cedula.getText();
        System.out.println(cedula);
        ResultSet respusta = data_base.buscarUsuario(cedula);
        System.out.println(respusta);
        if (respusta != null && cedula != null && !"".equals(cedula)){
            try { 
                c_nombre.setText(respusta.getString("nombre"));
                c_apellido.setText(respusta.getString("apellido"));
                c_contrasena.setText(respusta.getString("contrasenia"));
                c_rol.setText(respusta.getString("estado"));
            } catch (SQLException ex) {
                System.out.println("no existe ese campo que buscas en la db");
            }
        }
    }//GEN-LAST:event_buscarPersona

    private void c_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_rolActionPerformed
    
    
    public void alternInitComponents(){
        Image btn_eliminar = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_eliminar.png"));
        btn_eliminar = btn_eliminar.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_elinimar.setIcon(new ImageIcon(btn_eliminar));
        
        Image btn_editar = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_editar.png"));
        btn_editar = btn_editar.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_editar.setIcon(new ImageIcon(btn_editar));
        
        Image btn_ok = getToolkit().createImage(ClassLoader.getSystemResource("imagenes/btn_ok.png"));
        btn_ok = btn_ok.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        l_btn_ok.setIcon(new ImageIcon(btn_ok));
        
        this.setBackground(new Color (0, 0, 0, (int) (255 * (1 - 0.6))));
        
        Border emptyBorder = new EmptyBorder(0, 7, 0, 0);        
        l_btn_elinimar.setBorder(emptyBorder);       
        l_btn_editar.setBorder(emptyBorder);

        this.setVisible(true);
        this.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_apellido;
    private javax.swing.JTextField c_cedula;
    private javax.swing.JTextField c_contrasena;
    private javax.swing.JTextField c_nombre;
    private javax.swing.JTextField c_rol;
    private javax.swing.JLabel l_apellido;
    private javax.swing.JLabel l_btn_editar;
    private javax.swing.JLabel l_btn_elinimar;
    private javax.swing.JLabel l_btn_ok;
    private javax.swing.JLabel l_cedula;
    private javax.swing.JLabel l_contrasena;
    private javax.swing.JLabel l_contrasena1;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_respusta;
    // End of variables declaration//GEN-END:variables
}
