/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import clases.DataBase;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.ListSelectionModel;
import java.text.NumberFormat;
import java.util.Locale;

/**
 *
 * @author INSTRUCTOR
 */
public class PanelPedido extends javax.swing.JPanel {
    DefaultTableModel modelo;
    DataBase data_base;
    Mesas mesa;
    public PanelPedido(DataBase data_base,Mesas mesa) {
        this.mesa = mesa;
        this.data_base = data_base;
        initComponents();
        alternInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel5.setText("PEDIDO");

        jTable1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_factura", "Mesa", "Total", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void alternInitComponents(){
        modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setDefaultEditor(Object.class, null);
        jTable1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow != -1) {
                    Object id_factura = modelo.getValueAt(selectedRow, 0); // Columna 1
                    Object n_mesa = modelo.getValueAt(selectedRow, 1); // Columna 2
                    Object total = modelo.getValueAt(selectedRow, 2); // Columna 2
                    Object estado = modelo.getValueAt(selectedRow, 3); // Columna 2
                    int id_factura_int =Integer.parseInt((String) id_factura);
                    mesa.removerPanelPedido(id_factura_int);
                }
                revalidate();
                mesa.repaint();
                mesa.revalidate();
            }
        });
       cargaListaPedidos();
       
       
        this.setVisible(true);
        this.revalidate();
    }
    
    public void cargaListaPedidos(){
        ResultSet listado = this.data_base.consultaGeneral("factura");
        if(listado != null){
            try {
                modelo.setRowCount(0);
                do{
                    String id_factura = listado.getString("id_factura");
                    String id_mesa = listado.getString("id_mesa");
                    String total = listado.getString("total");
                    String estado = listado.getString("estado");
                    double numero = Double.parseDouble(total);

                    Locale locale = new Locale("es", "CO");
                    NumberFormat formatoMoneda = NumberFormat.getCurrencyInstance(locale);

                    String formatoMonedaString = formatoMoneda.format(numero);

                    Object[] fila = new Object[]{ id_factura,id_mesa, formatoMonedaString, estado};
                    modelo.addRow(fila);
                }while(listado.next());
            } catch (SQLException ex) {
                System.out.println("Error al extraer datos: "+ex.getMessage());
            }
        }else{
            System.out.println("LISTA VACIA");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
